### ISSUE TITLE
html export needs a tiny fix

### ISSUE THREAD

**Issue by vaibhaw-** [dozingcat/AsciiCam#1]
Brian,

The current exported HTML sets the background to black but doesn't set the font to white which leads completely black HTML file.

Here's a given HTML file output:
<html><head></title>Ascii Picture 2013-09-21-11-54-34</title></head><body><div style="background: black; letter-spacing: 3px;">

However simply adding the color and setting it to white fixes the html:

<html><head></title>Ascii Picture 2013-09-21-11-54-34</title></head><body><div style="background: black; letter-spacing: 3px; color: white">

Might be useful for some folks.

Also, can I file a request for enhancement? Would really love if there was a way to rotate the image while exporting a HTML.

**Comment by vaibhaw-** [comment]
Forgot the say thanks for your lovely app! :)

**Comment by dozingcat** [comment]
You're right, simple fix coming shortly. Thanks for the report!
