### ISSUE TITLE
Current version not available in play store

### ISSUE THREAD

**Issue by Krawei** [dozingcat/AsciiCam#13]
Dear team,

when I take  look in the playstore, the app's current version is v1.2.2, in F-Droid the version is v1.1.6.

What's the reason for this difference? Is there a flaw/bug in the build process?

Kind Regards, 

Krawei

**Comment by Krawei** [comment]
Dear Team, made a mistake....the topic is "Current version not available in F-Droid"

**Comment by Krawei** [comment]
Any updates here?

**Comment by Krawei** [comment]
@dozingcat How can we support here?

**Comment by dozingcat** [comment]
I've submitted a merge request to update the F-Droid release at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6517. Although I recommend using [Vector Camera](https://github.com/dozingcat/VectorCamera) if you can; it's available on F-Droid and Google Play.

**Comment by dozingcat** [comment]
The F-Droid update was accepted, it should show up in the next few days.
